# Generated by Django 4.0.5 on 2022-07-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=20)),
                ('releaseDate', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rating', models.IntegerField(choices=[(0, 'Not Good'), (1, 'Not Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Cool'), (5, 'Awesome')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musicians')),
            ],
        ),
    ]
