# Generated by Django 4.0.5 on 2022-07-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='facebook_id',
        ),
    ]
